package main

import _ "embed"

// instructionsText is the agent contract printed by the `instructions` command:
// how to act on a review through the `code-review` CLI. It lives in
// `instructions.md` so it can be edited as markdown rather than a Go string
// literal, and is embedded here in `backend` (rather than in `model`) so the CLI
// can print it while keeping `model` free of an embed dependency.
//
//go:embed instructions.md
var instructionsText string

// readmePointer is the short text stamped into a state file's `_readme` field
// and emitted by the GUI's "copy AI prompt" action. The full agent contract now
// lives in the `instructions` command rather than the file, so the field only
// points the reader at the CLI.
const readmePointer = "This review is managed by the 'code-review' tool. " +
	"Do not edit this file by hand. In this repository, on this branch, run " +
	"`code-review instructions` and follow it."
